Orthanc web
MSF-OCB/orthanc-docker-compose pull request #12
Opened 2021-05-18 06:48 UTC by ianso-msf

2021-05-18 07:36 UTC, ianso-msf reviewed
Great stuff!

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +    dets = mod_list[mstr]
I think here you need to make the REST call again instead of using the global variable.

The reason for this is that if the application restarts and then someone goes directly to a "details" page instead of passing by the index (for example by clicking "refresh" on an open page), then  this will cause an error because ``mod_list`` will be null.

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +def del_mod(mod):
I think you can inline this method in "delmodalities"? It's normally only worth extracting a method if you're going to call it more than once.

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/templates/addmod.html
> +    <title>Modalities Setting</title>
I would change the title to "MODALITIES - Add new device"

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/templates/details.html
> +    <title>Modalitie details</title>
I would change the title to "MODALITIES - Details for device {{m}}"

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/templates/index.html
> +  <title>Modalities short</title>
I would change the title to "MODALITIES - All devices"

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/templates/index.html
> +  <link rel="stylesheet" type="text/css" href="../static/css/style.css">
think this got changed from  ``href="{{ url_for('static', filename='css/style.css') }}"``

2021-05-18 07:36 UTC, ianso-msf commented on modalitiesconf/src/templates/index.html
> +            <!--th>Manufacturer</th>
as elsewhere you can remove all the commented out code

2021-05-18 08:34 UTC, R-VdP commented on modalitiesconf/src/templates/index.html
> +            <!--th>Manufacturer</th>
Also, I would call the "AET" column "AE Title", which is the standard term.

2021-05-18 08:54 UTC, R-VdP requested changes

2021-05-18 08:54 UTC, R-VdP commented on docker-compose.web.yml
> +    ports:
Absolutely, but you will need some traefik config to properly expose this app. We do this in the separate `docker-compose.dns_cert.yml` file, so that we can avoid needing to run Traefik during development.
We should not have any references to the `web` network in the main `docker-compose.yml`.

Very important indeed, is to not use `ports` but instead use `expose`, so that the port is only exposed on the docker network, and not on the host, to avoid any direct HTTP access bypassing Traefik.

For the Traefik config, I think we could add labels like this in `docker-compose.dns_cert.yml`:
```yml
orthanc-web:
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthanc-web-router.rule=Host(`local.pacs.ocb.msf.org`) && Path(`/ocb-admin`)"
      - "traefik.http.routers.orthanc-web-router.entrypoints=websecure"
      - "traefik.http.routers.orthanc-web-router.tls.certresolver=letsencrypt_dns"
      - "traefik.http.services.orthanc-web-service.loadbalancer.server.port=8081"
```

2021-05-18 08:54 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +def set_env(mods) :
Also, I would take such things as parameters to the script, rather than taking them from the environment. This will make the script a lot less fragile. There is a very easy to use library called argparse, I can show you multiple examples.

2021-05-18 08:54 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +    full_url = 'http://orthanc:8042/modalities/'+modname
Any escaping required here, to make sure that there cannot be any injection?

2021-05-18 08:54 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +        my_byte = response.read()
I don't understand this. What happens if the server returned an error?

2021-05-18 08:54 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +        return Response(my_data, 200)
Is it always 200? what if the server returned an error?

2021-05-18 12:38 UTC, sverachimsf commented on docker-compose.web.yml
> +    ports:
Hello,
thanks a lots for the remarks and suggestions and let's improve it!

1) Yep no problem. I will
 - modify the port definition
 - uncomment the network one
 - add a separate file with traefik config like done in other projects

2021-05-18 12:40 UTC, sverachimsf commented on docker-compose.web.yml
> +services:
@ianso-msf you mean remove docker.compose.web.yml? ok no pb

2021-05-18 13:00 UTC, sverachimsf commented on docker-compose.web.yml
> +    ports:
@R-VdP Sorry the docker-compose.dns_cert.yml is already there. Do we need another one? Maybe you mean to modify the current one? Thanks

2021-05-18 13:20 UTC, sverachimsf commented on docker-compose.web.yml
> +    ports:
So in the main compose I added:
orthanc-web:
    container_name: orthanc-web
    hostname: orthanc-web
    image: modalitiesconf/modalities_web:0.1
    expose:
      - 8081
    restart: unless-stopped
    networks:
      - default

and I will keep the compose.web for dev&test only

2021-05-18 13:35 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +        <p><h3>ADD A NEW DEVICE</h3></p>
ok

2021-05-18 13:35 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +    <!--script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script-->
ok

2021-05-18 13:37 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +            value={{m}}
well it works without but I can add quotes

2021-05-18 13:38 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +<!--
yep I am removing all comments (and saving outside code that might be used)

2021-05-18 13:42 UTC, R-VdP requested changes

2021-05-18 13:42 UTC, R-VdP commented on docker-compose.dns_cert.yml
> +      - "traefik.http.routers.orthanc-router.rule=Host(`local.pacs.ocb.msf.org`) && Path(`/ocb-admin`)"
This needs to be done for the `orthanc-web` service, not the `orthanc` service.

2021-05-18 13:42 UTC, R-VdP commented on docker-compose.dns_cert.yml
> +      - "traefik.http.services.orthanc-service.loadbalancer.server.port=8081"
This is for `orthanc-web`, now you have removed the correct port for `orthanc` and added a wrong one.
You should leave the for `orthanc`, but instead include the `orthanc-web` service in this file, and add the right labels to that one, to have all traffic on `https://local.pacs.ocb.msf.org/ocb-admin` routed to your `orthanc-web` container, and not to the main `orthanc` container.

The rest of the traffic, will still be routed to the main `orthanc` container.

2021-05-18 13:43 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +            <td>N/A</td>
ok, 5, but ok, no pb

2021-05-18 13:48 UTC, R-VdP commented on docker-compose.web.yml
> +    ports:
@sverachimsf you add a section exactly like the one I posted above, to the existing `docker-compose.dns_cert.yml` file, to extend the `orthanc-web` service with the needed options to have Traefik route traffic to it.

In the `docker-compose.dns_cert.yml`, you will therefore have two services defined, `orthanc` and `orthanc-web`, each adding options to the corresponding services in the main `docker-compose.yml` file.

It would look something like this: (**how the routers and services for the two containers have different names, this is very important!**)
```yml
version: "3.8"

services:

  orthanc:
    ports:
      - target: 4242
        published: 104
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthanc-router.rule=Host(`local.pacs.ocb.msf.org`)"
      - "traefik.http.routers.orthanc-router.entrypoints=websecure"
      - "traefik.http.routers.orthanc-router.tls.certresolver=letsencrypt_dns"
      - "traefik.http.services.orthanc-service.loadbalancer.server.port=8042"

  orthanc-web:
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthanc-web-router.rule=Host(`local.pacs.ocb.msf.org`) && Path(`/ocb-admin`)"
      - "traefik.http.routers.orthanc-web-router.entrypoints=websecure"
      - "traefik.http.routers.orthanc-web-router.tls.certresolver=letsencrypt_dns"
      - "traefik.http.services.orthanc-web-service.loadbalancer.server.port=8081"

networks:
  web:
    external: true
```

2021-05-18 13:52 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    dets = mod_list[mstr]
Actually I have some douts... that's why I mentioned you about the global variable time ago. I used the global variable becuase actually I wanted to avoid to 'over charge' & 'stress' the server with too many requests. In this use case you wouldn't go to the details page from any other page than the index which is the result of a rest call (get) for the full list. The only argument indeed would be the "refresh" ... I will think about

2021-05-18 13:54 UTC, sverachimsf commented on docker-compose.web.yml
> +    ports:
Oh yes, didn't think about. Ok I will modify it accordingly

2021-05-18 15:15 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    password = 'stupid'
Yep you are right.  No need for modularity in this case as the authentication indeed it will happen only once for the whole site at the beginning and not to access any resource

2021-05-18 15:20 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +def del_mod(mod):
Totally agree with you. I dunno why I was thinking that the function would have been called somewhere else. Probably I was just tired ;)

2021-05-18 15:22 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +    <title>Modalities Setting</title>
alrigh

2021-05-18 15:24 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +    <title>Modalitie details</title>
alright

2021-05-18 15:24 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +  <title>Modalities short</title>
oki

2021-05-18 15:26 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +  <link rel="stylesheet" type="text/css" href="../static/css/style.css">
yep when trying to understand why on chrome wouldn't all changes were not visible but the problem was in chache of the browser. I put back the the templating syntax

2021-05-18 15:32 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +            <!--th>Manufacturer</th>
oki. Just be aware that the result might look "ugly" or simply not the best at a first glance, that's why sometimes we are forced to go for a choice which is nice from an aesthetic point of view and less from the functional one and even less from other point of views ... as long as we all agree, everything is fine

2021-05-18 15:34 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        return Response(my_data, 200)
Nope obviously not. Error handling was left for a second cicle of dev. To be correctly done

2021-05-19 08:16 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +    <title>Modalities Setting</title>
ok but as far as i remember the title in the head of a html page is not dispalyed ... but it is ok i can set as you like

2021-05-19 08:45 UTC, sverachimsf commented on docker-compose.dns_cert.yml
> +      - "traefik.http.services.orthanc-service.loadbalancer.server.port=8081"
We need two different services dealing with the two traffics that was not claer at the beginning. Ok no pb

2021-05-19 08:49 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        return Response(my_data, 200)
nope of course not. Actually i didn't ask for a review of this code as it was in pure testing. Error handing has to be completed
I can add some catch up of type 500 errors

2021-05-19 09:06 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +  <link rel="stylesheet" type="text/css" href="../static/css/style.css">
yep it was to test the url_for() as I couldn't see the style changes done in the css file. The problem was the chache of chrome. Corrected

2021-05-19 09:27 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +def set_env(mods) :
- ok I will remove set_env. 
- regarding the practise to pass argument to a function I agree it is generally better indeed. It is an improvement in this case. And yes if you have examples and want to share, thanks. I will have a look at the library argparse though.

2021-05-19 11:48 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    full_url = 'http://orthanc:8042/modalities/'+modname
Which one do you prefere? Apparently the first one doesn't protect but in the official flask page they say to use escape to avoid enjection ... but https://realpython.com/prevent-python-sql-injection/ they say to pass named parameter and the simple escape() doesn't protect

- urltest='{}'.format(escape(location)) #string
- urltest2="%s'", (location, ) #tuple
- urltest3=" %(location)s", {'location': location} #4 

pff what shall I use? pls advise

2021-05-20 06:53 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    full_url = 'http://orthanc:8042/modalities?expand' #or the iamge like : osimis/orthanc//orthanc:8042/modalities?expand
added a secrets file. In service orthanc-web:
env_file:
      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets

2021-05-20 07:31 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +    full_url = 'http://orthanc:8042/modalities/'+modname
There is a standard function, `urllib.parse.quote`, that does what you want:

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote

2021-05-21 06:21 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +registereduser = os.getenv("ORTHANC__REGISTERED_USERS")
this this is an unused variable?

2021-05-21 06:23 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +    return portn.isdigit()
and less that 65535 :-)

2021-05-21 06:23 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +    if not IP_REGEX.match(ipaddr):
you can also do ```return IP_REGEX.match(ipaddr)```

2021-05-21 06:26 UTC, ianso-msf commented on modalitiesconf/src/templates/details.html
> +        <p><a href="{{url_for('index')}}">HOME</a><h3></h3></p>
sorry to be a PIA but I would suggest ``` <h3><a href="{{url_for('index')}}">HOME</a></h3>``` - small thing I know :-)

2021-05-21 06:27 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    full_url = 'http://orthanc:8042/modalities/'+modname
well to prevent injection in general like that we use escape(url) as suggested by Flask doc

2021-05-21 06:32 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +registereduser = os.getenv("ORTHANC__REGISTERED_USERS")
Nope in the current version, I just added because I wanted to test  how to access key and value and in this way to extract username and password from only that orthanc variable but I haven't find yet, well working. I can remove it if you like and test it later. It is not important

2021-05-21 06:33 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    return portn.isdigit()
indeed thanks

2021-05-21 06:33 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    if not IP_REGEX.match(ipaddr):
indeed

2021-05-21 06:34 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +        <p><a href="{{url_for('index')}}">HOME</a><h3></h3></p>
Ouops forgot this. Sorry I will fix it

2021-05-21 06:48 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    return portn.isdigit()
you like this ? ;-)

def valid_port(portn):
    return (portn.isdigit() and (0 < portn <= 65535))

2021-05-21 06:49 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    return portn.isdigit()
few test and then I will push and open a PR

2021-05-21 06:50 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        my_byte = response.read()
I am caching errors like that:

  if resp.decode('utf-8') != '':
            return Response('Something went wrong ...', status=400)
        else :
            return index()

2021-05-21 07:38 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +    <title>Modalitie details</title>
Actually visually it looks better only MODALITIES in title ... so I removed second part unless you absolutly want it with ;-)

2021-05-21 07:38 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +  <title>Modalities short</title>
same remark here ... visually it looks better only MODALITIES ....

2021-05-21 09:01 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +        <p><a href="{{url_for('index')}}">HOME</a><h3></h3></p>
Actually I am doing some more stying. I moved up the a element with HOME link at same level of title.

2021-05-21 09:36 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    dets = mod_list[mstr]
I changed the logic with one more REST call even though it is not optimized. The 'refresh' works, I guess the value is chached or stored somewhere during the whole session, but I am not sure. In the meantime I leav it as it is with one more REST call

2021-05-21 09:37 UTC, sverachimsf commented on modalitiesconf/src/templates/index.html
> +            <td>N/A</td>
and I centered the text

2021-05-21 09:40 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +def set_env(mods) :
Added a secret file also for the orthanc-web service. 'Sensitive' or private data are rasonably secured

2021-05-21 09:45 UTC, sverachimsf commented
I would close this PR since I pushed new modif with corrections. Cheers

2021-05-21 09:45 UTC, closed without merging