Orthanc web
MSF-OCB/orthanc-docker-compose pull request #13
Opened 2021-05-21 09:47 UTC by sverachimsf

Voilà, did corrections and added few styling and code improvments

2021-05-21 10:09 UTC, R-VdP requested changes

2021-05-21 10:09 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +def valid_ip(ipaddr):
We can do this in a more readable way without needing a regex:
```python
import ipaddress

try:
  ipaddress.ip_address(ipaddr)
  return true
except ValueError:
  return false
```

2021-05-21 10:09 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +        return Response('Something wrong happened ...', status=400)
This will be fun to debug when the user reports the system saying that something wrong happened... Maybe it would be good to include a bit more detail in the error message to help our future selfs ;)

2021-05-21 10:09 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +    url = escape(ORTHANC_URL+'modalities/'+ mstr)
I'd suggest using `urllib.parse.quote()`, Flasks's escape is made to escape entries that could cause **HTML injection** not **URL injection**. The characters that are problematic differ wildly between the two, e.g. a space is not valid in a URL.

2021-05-21 10:09 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +            return Response('Something went wrong ...', status=400)
Same as above, be kind to the future people debugging this.

2021-05-21 11:31 UTC, ianso-msf commented on modalitiesconf/src/modalities_web.py
> +registereduser = os.getenv("ORTHANC__REGISTERED_USERS")
unused variable I think :-)

2021-05-21 11:34 UTC, ianso-msf commented on modalitiesconf/src/templates/addmod.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
I would put some whitespace between ```MODALITIES<a ``` otherwise they will be right next to each other on the screen

2021-05-21 11:35 UTC, ianso-msf commented on modalitiesconf/src/templates/details.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
likewise

2021-05-21 12:20 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        "AET":request.form.get('aettitle'),
alrigh

2021-05-21 12:30 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    modstr=str(modname)
I just didn't want to over complicate this code but ok no pb I will use quote

2021-05-21 12:31 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +def valid_ip(ipaddr):
indeed try & except was the next step, alrigh

2021-05-21 12:36 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        return Response('Something wrong happened ...', status=400)
Well ... I think you know better than me that when debugging we won't go to see this message (to user) but directly the server logs ;-) but I agree that error messages must be as pricises as we can.

2021-05-21 12:36 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +    url = escape(ORTHANC_URL+'modalities/'+ mstr)
alrigh

2021-05-21 12:41 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +            return Response('Something went wrong ...', status=400)
:-) I am extremely nice with them! That's why I won't "pollute" them with too techy details ... but ok more precises message I agree

2021-05-21 12:41 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +registereduser = os.getenv("ORTHANC__REGISTERED_USERS")
yep I will remove it

2021-05-21 12:42 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
okay

2021-05-21 12:43 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
fine

2021-05-21 12:45 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +def valid_ip(ipaddr):
Oh sorry didn't notice the notation ipaddress.ip_address(ipaddr) to validate ip(s) without regex .... nice! I like that

2021-05-21 12:47 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        resp = response.read()
ok

2021-05-21 12:53 UTC, sverachimsf commented on docker-compose.web.yml
> +version: "3.8"
actually not even for testing

2021-05-21 13:03 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +    modstr=str(modname)
It's not overcomplicating, all user input should always be properly escaped, this is the bare essential to avoid many types of injection and hijacking attacks.

2021-05-21 13:04 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +        return Response('Something wrong happened ...', status=400)
Well, you are not logging anything to the server logs either... So yes, I would agree, but then you need to set up logging :)

2021-05-21 13:17 UTC, sverachimsf commented on docker-compose.web.yml
> +version: "3.8"
no for testing it is needed same as docker-compose.local.yml in the way ports are defined, I will keep it

2021-05-21 14:08 UTC, sverachimsf commented on modalitiesconf/src/templates/addmod.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
I don't want to be mean but are you sure it is better to use whitespace? I just tried and I need a very long serie od &nbsp; ... Here they actually state the opposite :-) 
https://mailtrap.io/blog/nbsp/
"When not to use &nbsp
You’ve got to admit, the code above is not very readable. At the same time, creating multiple spaces with the use of &nbsp is a poor design practice. What may look OK on your screen is almost certain to collapse in an uncontrollable way on the user’s end because of the enormous diversity of screen sizes and resolutions. 

Because of that, paddings, margins, or width are nearly always better approaches when designing responsive pages. We’ll discuss them all in the following chapter. &nbsp is a useful way of keeping characters together, but should probably be used just for that purpose."  

So how about to keep the margins? :-)

2021-05-25 12:32 UTC, sverachimsf commented on modalitiesconf/src/modalities_web.py
> +        resp = response.read()
raise_for_status()  is a method available in the module "requests" that I am not using to build the request object.

2021-05-25 12:41 UTC, R-VdP commented on modalitiesconf/src/modalities_web.py
> +        resp = response.read()
Ah, I didn't notice. `urllib.request` is rather low-level, and the doc recommends using `requests`, which uses `urllib.request` under the hood.

Otherwise you'll probably need to write this kind of error-handling code yourself...

2021-05-25 14:08 UTC, sverachimsf commented on modalitiesconf/src/templates/details.html
> +      <h2>MODALITIES<a style="margin-left:197%; color:#333333; text-decoration:underline" href="{{url_for('index')}}">HOME</a></h2>
keeping margins

2021-05-27 08:58 UTC, R-VdP requested changes

2021-05-27 08:58 UTC, R-VdP commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
I guess you need `orthanc_secrets` as well, for the password to authenticate to Orthanc.

2021-06-07 09:51 UTC, sverachimsf commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
The file web_secrets contains the same orthanc credentials in format  
AUTH_USERNAME=XXXX
AUTH_PASSWORD=XXXX
they are not used to authenticate to the Admin UI. With @ianso-msf at the beginning we decided not to implement the authentication to the admin gui in this first release. So removing the ORTHANC_URL variable, this file, renamed 'orthanc_admin_ui_secrets' contains same credentials to authenticate to orthanc. I know this violates the 'one single source of true' principle and that 'orthanc_admin_ui_secrets' should contain credentials for the admin gui. The improvement would be to modify the compose in the orthan-web service section with:

env_file:
      ${MSFOCB_SECRETS_DIRECTORY}/orthanc_secrets
      ${MSFOCB_SECRETS_DIRECTORY}/orthanc_admin_ui_secrets
environment:
     ORTHANC_URL=http://orthanc
     ORTHANC_PORT=8042

and then to add a login page for the admin gui. @ianso-msf @R-VdP what do you think?

2021-06-07 09:57 UTC, R-VdP commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
@sverachimsf except that right now the password in that file is not the same as that in the other one...

If they are the same, why then don't you just use the already existing file which has the same password, and read the json value to extract the password? The seems easier than duplicating it into a second secrets file, no?

2021-06-07 10:32 UTC, sverachimsf commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
@R-VdP totally agree we should extract the password from the existing file, as I just mentioned. I just made the web_secrets file, with the format key=value instead of VAR={"username": "password"} as I couldn't make extract the json value like with VAR["username"]. I think we need to extract also the "username", no? 
I think I tried something like VAR.keys or VAR.values but it didn't work.... I need to better search as I coudn't find the right method

2021-06-07 10:44 UTC, R-VdP commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
In your python script, you use `json.load` to parse the json string from the environment variable, and then you will get a standard python dictionary from which you can get the values.

I would pass the env var as an argument to the python script rather than reading it from the env in the python script itself, to make the script's dependencies explicit.
Then you take the value of the argument, and parse it with `json.load`.

Look at argparse for the argument parsing, it's very easy to use, an example can be found here: https://github.com/MSF-OCB/NixOS/blob/15f124f37e6beaf490d36e4bbb3a8f0846b0ca17/scripts/secrets/decrypt_server_secrets.py#L18

2021-06-07 12:03 UTC, sverachimsf commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
my python script is itself an argument of the call to uwsgi inside the bash script launch.sh so this implies a modif of the bash script too

2021-06-07 12:24 UTC, R-VdP commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
Looks like you can pass variable through uwsgi to the python script using the `--pyargv` option.

2021-06-07 14:24 UTC, sverachimsf commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
this is ok, I can use this option --pyargv "secrets_fle"  the point is that the secrets_file should be inside the container file system, meaning that inside Dockerfile I should add an instruction to copy from the host file system to the container file system something like: 

COPY ${MSFOCB_SECRETS_DIRECTORY}/orthanc_secrets   ./orthanc_secrets 

but then I would be able to access the orthanc_secrets file without the need to add arguments to the call to uwsgi otherwise it would be a redundancy .... or am I wrong?

2021-06-07 17:32 UTC, R-VdP commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
Well, `COPY` is a Dockerfile instruction, used at build time. At run time you would use a bind mount to mount a file from the host into your container.

But I don't think that you need to do this, you can just pass the environment variable into your container (by setting the secrets file as env_file, like we did for orthanc), and then in your `launch.sh` you do something like
```
uwsgi <...> --pyargv "${ENV_VAR}"
```
with `ENV_VAR` being the actual name of the secret that you want to pass into your script.
Like this, you avoid unneeded bind mounts, and at the same time you don't leak the value of the secret into the logs of the app.

2021-08-02 15:37 UTC, ianso-msf commented on docker-compose.yml
> +      ${MSFOCB_SECRETS_DIRECTORY}/web_secrets
decided to stick with environment variables

2021-08-02 15:38 UTC, ianso-msf approved these changes
ok

2021-08-02 15:40 UTC, merged